service: aws-ses-serverless-example

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Resource: "*"
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents

plugins:
  - serverless-webpack

functions:
  sendMail:
    handler: handler.sendMail
    description: Send email using SES service.
    memorySize: 128
    timeout: 10
    environment:
      FROM_EMAIL: ${opt:from}
      TO_EMAIL: ${opt:to}
    iamRoleStatements:
      - Effect: Allow
        Resource: "*"
        Action:
          - ses:SendEmail
          - ses:SendRawEmail
          - logs:CreateLogGroup
          - logs:CreateLogStream
          - logs:PutLogEvents
    events:
      - http:
          path: /
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
